apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cicd-project
  region: us-east-1

# selecting namespaces in fargate profile we can only deploy to these namespaces
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system

